---
title: "FinalProject"
author: "Nicholas Shuble,Luke Pedersen, Joseph Downs"
date: "2023-11-28"
output: html_document
---



```{r}
library(readr)
# Opening the csv file
fifa_players <- read_csv("archive/fifa_players.csv")
View(fifa_players)

```

```{r}
library(dplyr)
library(ggplot2)
#Selecting the relevant attributes from the dataset as we do not need all of them
fifa_players <- fifa_players  %>%
  select(name, age, height_cm, weight_kgs, positions, nationality, overall_rating, potential, value_euro, wage_euro, preferred_foot, release_clause_euro, crossing, finishing, heading_accuracy, dribbling, curve, acceleration, agility, jumping, stamina)
```

Do taller players have better heading rating?
```{r}
#Create a wrangled data set that only includes necessary values
heights_heading <- fifa_palyers %>% 
  select(height_cm,heading_accuracy)
#Create a scatterplot
ggplot(heights_heading,aes(x = height_cm, y = heading_accuracy)) +
  geom_point(size = 0.7,color = 'red') +
#Create a line of best fit for the scatterplot
  stat_smooth(method = "lm",
        col = "black", se = FALSE, size = 1) +
  labs(title = paste("Height vs. Heading Accuracy")) +
  theme_minimal()
```



```{r}

```

```{r}
fifa_players %>%
 filter(potential >= 59L & potential <= 95L) %>%
 ggplot() +
  aes(x = potential, y = release_clause_euro) +
  geom_line(colour = "#111C46") +
  labs(x = "Player potential", y = "Release Clause (euros)", title = "Potential vs Release Clause") +
  theme_minimal()
```

```{r}
fifa_players %>%
 filter(overall_rating >= 60L & overall_rating <= 94L) %>%
 ggplot() +
  aes(x = overall_rating, y = wage_euro) +
  geom_point(shape = "circle", size = 0.5, colour = "#B22222") +
  geom_smooth(span = 0.75) +
  labs(
    x = "Wage (euros)",
    y = "Overall Rating",
    title = "Wage vs Overall Rating"
  ) +
  theme_minimal()
```



```{r pressure, echo=True}
library(ggplot2)

ggplot(fifa_players, aes(x = preferred_foot, y = finishing, fill = preferred_foot)) +
  geom_boxplot() +
  labs(title = "Finishing Ability by Preferred Foot",
       x = "Preferred Foot",
       y = "Finishing Rating") +
  theme_minimal()


library(ggplot2)

data("fifa_players")

library(dplyr)

library(knitr)

library(kableExtra)

summaryTable <- fifa_players %>%

group_by(preferred_foot) %>%

summarize(count = n(),

finishing_min = min(finishing,na.rm = TRUE),

finishing_q1 = quantile(finishing, probs = .25,na.rm = TRUE),

finishing_median = median(finishing,na.rm = TRUE),

finishing_q3 = quantile(finishing, probs = .75,na.rm = TRUE),

finishing_max = max(finishing,na.rm = TRUE),

finishing_mean = mean(finishing,na.rm = TRUE),

finishing_std = sd(finishing,na.rm = TRUE))
#Create the cleaned table
summaryTable %>%
  kable(
    digits = 2,
    format.args = list(big.mark = ","),
    caption = "Summary Statistics for Preferred Foot-Finishing",
    col.names = c('preferred_foot','count',"finishing_min",'finishing_q1','finishing_median',
                  'finishing_q3','finishing_max','finishing_mean','finishing_std'),
    align = c("l", rep("c", 8)),
    booktabs = TRUE
  ) %>%
kableExtra::kable_classic()


```


